### ISSUE TITLE
error when data back in strapi backend

### ISSUE THREAD

**Issue by cna-so** [bradtraversy/dj-events-backend#1]
i copy your codes and threw on a error 
thid is postman error 
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Your filters contain a field 'user' that doesn't appear on your model definition nor it's relations"
}

**Comment by zachshirow** [comment]
@sina-soleymanzadeh Hey there friend, Some of the backend code or the fetching of the api in the frontend might not work. This is because a new version of strapi has been released and the api has changed. You can visit the official documentation website of strapi to see the changes in api and modify you code according to these changes. 

https://docs.strapi.io/
